### PR TITLE
Resolve es3 build issue

### LINKED ISSUE #344: Unable to resolve signature of method decorator when called as an expression
The example test case code does not compile in TypeScript 2.2.1:

```
import { Expect, TestCase, TestFixture } from "alsatian";

@TestFixture("Example Test Fixture")
export class ExampleTestFixture {

  @TestCase(1, 2)
  @TestCase(4, 5)
  public exampleTest(preIteratedValue: number, expected: number) {
    Expect(preIteratedValue++).toBe(expected);
  }
}
```

I get an error on the `@TestCase` line:

```
error TS1241: Unable to resolve signature of method decorator when called as an expression.
            Supplied parameters do not match any signature of call target.
```

My `tsconfig.json` is as follows:

```
{
  "compilerOptions": {
    "moduleResolution": "node",
    "experimentalDecorators": true
  },
  "include": [
    "./**/*.test.ts"
  ]
}
```

### PR DESCRIPTION
**Pull request by jamesrichford**
# Description
Resolves building with target of es3 (closes #344)

# Checklist

- [x] I am an awesome developer and proud of my code
- [x] I added / updated / removed relevant unit or integration tests to prove my change works
- [x] I ran all tests using ```npm test``` to make sure everything else still works
- [x] I ran ```npm run review``` to ensure the code adheres to the repository standards

### CODE REVIEW

**Comment by Jameskmonger** [comment]
Can you change `Object` to `object` when using it as a type? See https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html

**Comment by jamesrichford** [comment]
@jameskmonger should all be good now :)
