### ISSUE TITLE
Unable to resolve signature of method decorator when called as an expression

### ISSUE THREAD

**Issue by Jameskmonger** [alsatian-test/alsatian#344]
The example test case code does not compile in TypeScript 2.2.1:

```
import { Expect, TestCase, TestFixture } from "alsatian";

@TestFixture("Example Test Fixture")
export class ExampleTestFixture {

  @TestCase(1, 2)
  @TestCase(4, 5)
  public exampleTest(preIteratedValue: number, expected: number) {
    Expect(preIteratedValue++).toBe(expected);
  }
}
```

I get an error on the `@TestCase` line:

```
error TS1241: Unable to resolve signature of method decorator when called as an expression.
            Supplied parameters do not match any signature of call target.
```

My `tsconfig.json` is as follows:

```
{
  "compilerOptions": {
    "moduleResolution": "node",
    "experimentalDecorators": true
  },
  "include": [
    "./**/*.test.ts"
  ]
}
```

**Comment by Jameskmonger** [comment]
This appears to be resolved by adding `ES2016` as the target in `tsconfig.json`:

https://github.com/Microsoft/TypeScript/issues/9143#issuecomment-226268252

It may be worth adding this to the documentation.

**Comment by jamesrichford** [comment]
This looks like it's a TypeScript bug to me. If you make the third argument of a method decorator optional TypeScript es3 is fine with it, even if this data isn't available in es3 keep the API contract and send null? Very confusing anyway I'll send in a PR to change the arguments to optional

**Comment by jamesrichford** [comment]
@Jameskmonger this should be fixed in 1.3.1 :)
